### PR TITLE
Handle weird Linux edge cases.

### PR DESCRIPTION
**Pull request by nkrapivin**
the title.
pug.

### CODE REVIEW

**Comment by DragoniteSpam** [comment]
#JustLinuxThings

**Comment by JujuAdams** [comment]
Please remove everything that is not a relevant change e.g. gumshoe.yyp

**Comment by nkrapivin** [comment]
Done.

**Comment by JujuAdams** [comment]
Looks good! Couple requests aimed at cleaning up global namespace:
1. Please make `global.gumshoe_force_lower_case` an optional argument. I don't mind breaking compatibility and making this a GMS2.3.7+ library so feel free to rewrite the parameters using the newer syntax
2. Please make `global.__gumshoe_*` "private" globals into statics inside the function itself

I really like the comments you've put in, those are very helpful for developers to understand the differences. Thank you for putting those in.

**Comment by nkrapivin** [comment]
> Looks good! Couple requests aimed at cleaning up global namespace:
> 
> 1. Please make `global.gumshoe_force_lower_case` an optional argument. I don't mind breaking compatibility and making this a GMS2.3.7+ library so feel free to rewrite the parameters using the newer syntax
> 2. Please make `global.__gumshoe_*` "private" globals into statics inside the function itself
> 
> I really like the comments you've put in, those are very helpful for developers to understand the differences. Thank you for putting those in.

Updated. (also I do care about 2.3.6 a bit ;-;)

**Comment by JujuAdams** [comment]
Perfect! Thank you Nik

**Pull request merged**
